name: backend-test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v6
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          gleam-version: "1.16.0"
          rebar3-version: "3"
          # elixir-version: "1"
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: backend/build/packages
          key: ${{ runner.os }}-gleam-${{ hashFiles('backend/manifest.toml') }}
          restore-keys: |
            ${{ runner.os }}-gleam-
      - name: Check format
        run: gleam format --check src test
      - name: Generate skir
        run: npx skir@1.2 gen
      - name: Download dependencies
        run: gleam deps download
      - name: Type check
        run: gleam check
      - name: Lint
        run: gleam run -m lint
      - name: Run tests
        run: gleam test
